spring:
  datasource:
    url: jdbc:h2:file:~/estoque
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    console.enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true

server:
  port: 8080